application:
  name: docker_validator_netcore
  project: project-docker-syntax-checker
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: docker_validator_netcore
    paths:
    - /*
