application:
  name: docker_syntax_checker
  project: syntaxchecker
  cloud_region: aws/eu-west-3
  publicly_accessible: true
routers:
- name: main
  routes:
  - application_name: docker_syntax_checker
    paths:
    - /*
